#ifndef CONFIG_H_
#define CONFIG_H_

#define CONFIG_GAME_TIMER_PERIOD 40.0E-3f

#define CONFIG_MAX_PLAYER_MISSILES 4
#define CONFIG_MAX_ENEMY_MISSILES  7
#define CONFIG_MAX_PLANE_MISSILES  1
#define CONFIG_MAX_TOTAL_MISSILES  \
  (CONFIG_MAX_ENEMY_MISSILES +     \
   CONFIG_MAX_PLAYER_MISSILES +    \
   CONFIG_MAX_PLANE_MISSILES)

// Speed of enemy missile (pixels/sec)
#define CONFIG_ENEMY_MISSILE_DISTANCE_PER_SECOND 35
#define CONFIG_ENEMY_MISSILE_DISTANCE_PER_TICK \
  (CONFIG_ENEMY_MISSILE_DISTANCE_PER_SECOND * CONFIG_GAME_TIMER_PERIOD)

// Speed of player missile (pixels/sec)
#define CONFIG_PLAYER_MISSILE_DISTANCE_PER_SECOND 350
#define CONFIG_PLAYER_MISSILE_DISTANCE_PER_TICK \
  (CONFIG_PLAYER_MISSILE_DISTANCE_PER_SECOND * CONFIG_GAME_TIMER_PERIOD)

// How fast explosion radius changes (pixels/sec)
#define CONFIG_EXPLOSION_RADIUS_CHANGE_PER_SECOND 30
#define CONFIG_EXPLOSION_RADIUS_CHANGE_PER_TICK \
  (CONFIG_EXPLOSION_RADIUS_CHANGE_PER_SECOND * CONFIG_GAME_TIMER_PERIOD)
#define CONFIG_EXPLOSION_MAX_RADIUS 25

// Speed of tank (pixels/sec)
#define CONFIG_TANK_DISTANCE_PER_SECOND 60
#define CONFIG_TANK_DISTANCE_PER_TICK \
  (CONFIG_TANK_DISTANCE_PER_SECOND * CONFIG_GAME_TIMER_PERIOD)

// TANK off-screen time
#define CONFIG_TANK_IDLE_TIME_SECONDS 2.0f
#define CONFIG_TANK_IDLE_TIME_TICKS \
  ((uint32_t)(CONFIG_TANK_IDLE_TIME_SECONDS / CONFIG_GAME_TIMER_PERIOD))

// Tank size :: body, wheels, gun
#define CONFIG_TANK_BODY_WIDTH  5 * 5
#define CONFIG_TANK_BODY_HEIGHT 5 * 5
#define CONFIG_TANK_WHEELS_WIDTH 2 * 5
#define CONFIG_TANK_WHEELS_HEIGHT 7 * 5
#define CONFIG_TANK_GUN_WIDTH  1 * 5
#define CONFIG_TANK_GUN_HEIGHT 4 * 5

// Colors
#define CONFIG_COLOR_BACKGROUND rgb565(0, 128, 64) // A darker, richer green


#define CONFIG_COLOR_CURSOR rgb565(0, 128, 64)
#define CONFIG_COLOR_STATUS WHITE

#define CONFIG_COLOR_ENEMY_MISSILE  RED
#define CONFIG_COLOR_PLAYER_MISSILE rgb565(255, 105, 180) // A vibrant pink

#define CONFIG_COLOR_PLANE_MISSILE  BLUE

#define CONFIG_COLOR_TANK PURPLE
#define CONFIG_COLOR_WHEELS BLACK

#endif // CONFIG_H_
